import { LIVE_IOCS_CACHE_KEY, fetchLiveIocs, type LiveIocsResponse } from '../routes/live-iocs';

export const BLOCKLIST_KV_PREFIX = 'blocklist:';
/** Single consolidated KV key — previously 4 separate keys (pfsense,
 *  iptables, suricata, meta) cost 4 writes/day. One key costs 1. */
export const BLOCKLIST_KV_ALL_KEY = 'blocklist:all';
const CACHE_TTL = 86_400; // 24h

export interface BlocklistSet {
  pfsense: string;
  iptables: string;
  suricata: string;
  ip_count: number;
  generated_at: string;
}

let sidCounter = 9_000_000;

/**
 * Strict bare-IPv4 (optionally /CIDR) validator. Feed IOC values flow into
 * generated iptables/Suricata rule text by string interpolation, so a value
 * containing spaces/quotes/newlines would inject attacker-controlled rules
 * into the downloadable blocklist (some upstream parsers — e.g. TweetFeed —
 * don't format-check the value). Anything that is not a clean dotted-quad
 * (each octet 0–255), with an optional /0–32 suffix, is dropped before it can
 * reach a rule line.
 */
const STRICT_IPV4 =
  /^(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\/(?:3[0-2]|[12]?\d))?$/;

function sanitizeIps(ips: string[]): string[] {
  return ips.filter((ip) => STRICT_IPV4.test(ip));
}

function buildPfSense(ips: string[]): string {
  if (ips.length === 0) return '# No IPs available';
  return ips.join('\n');
}

function buildIptables(ips: string[]): string {
  if (ips.length === 0) return '#!/bin/sh\n# No IPs available\n';
  const lines = [
    '#!/bin/sh',
    '# Generated by pranithjain.qzz.io',
    '# iptables blocklist — apply with: iptables-restore < this-file',
  ];
  for (const ip of ips) {
    lines.push(`-A INPUT -s ${ip} -j DROP`, `-A FORWARD -s ${ip} -j DROP`);
  }
  return lines.join('\n');
}

function buildSuricata(ips: string[]): string {
  if (ips.length === 0) return '# No Suricata rules generated — no IPs available\n';
  const ts = new Date().toISOString().slice(0, 10);
  const header = [
    `# Suricata drop rules — generated ${ts} by pranithjain.qzz.io`,
    `# ${ips.length} IPs from live threat intelligence feeds`,
    '',
  ];
  const rules = ips.map((ip) => {
    const sid = sidCounter++;
    return `drop ip ${ip} any -> any any (msg:"BLOCKLIST malicious IP ${ip}"; classtype:trojan-activity; sid:${sid}; rev:1;)`;
  });
  return header.join('\n') + '\n' + rules.join('\n') + '\n';
}

export async function buildBlocklists(
  kv?: KVNamespace,
  executionCtx?: { waitUntil: (p: Promise<unknown>) => void }
): Promise<BlocklistSet> {
  // Try CF cache first, then live fetch. `caches.default` is dereferenced
  // guarded: it is a read-through optimisation, and an unavailable Cache API
  // must cost a live fetch rather than throwing out of `buildBlocklists` — which
  // runs both on the hourly cron and at the top of three request routes.
  const cache = (() => {
    try {
      return (caches as unknown as { default?: Cache }).default ?? null;
    } catch {
      return null;
    }
  })();
  const cached = await cache?.match(new Request(LIVE_IOCS_CACHE_KEY)).catch(() => undefined);
  let data: LiveIocsResponse | null = null;
  if (cached) {
    try {
      data = (await cached.json()) as LiveIocsResponse;
    } catch {
      /* ignore */
    }
  }
  if (!data) {
    try {
      data = await fetchLiveIocs(executionCtx, kv);
    } catch {
      return emptySet();
    }
  }

  const ips = sanitizeIps([...new Set(data.items.filter((i) => i.kind === 'ip').map((i) => i.value))]).sort();
  const generated_at = new Date().toISOString();
  const result: BlocklistSet = {
    pfsense: buildPfSense(ips),
    iptables: buildIptables(ips),
    suricata: buildSuricata(ips),
    ip_count: ips.length,
    generated_at,
  };

  // Write to KV — single consolidated key instead of 4 separate keys.
  // Saves 3 KV writes/day (4→1) within the free-tier budget.
  if (kv) {
    try {
      await kv.put(
        BLOCKLIST_KV_ALL_KEY,
        JSON.stringify({
          pfsense: result.pfsense,
          iptables: result.iptables,
          suricata: result.suricata,
          ip_count: ips.length,
          generated_at,
        }),
        { expirationTtl: CACHE_TTL }
      );
    } catch {
      /* ignore - handlers fall back to live gen */
    }
  }

  return result;
}

function emptySet(): BlocklistSet {
  const ts = new Date().toISOString();
  return {
    pfsense: '# No IPs available',
    iptables: '#!/bin/sh\n# No IPs available\n',
    suricata: '# No Suricata rules generated — no IPs available\n',
    ip_count: 0,
    generated_at: ts,
  };
}
