#!/usr/bin/env python3
"""
cloc-style LOC counter.

Counts, per language: blank lines, comment lines, and code lines.
Operates on `git ls-files` so .gitignore'd paths (node_modules, dist,
.ssr-build, coverage) are excluded by construction.

Comment rules per language family:
  c-family (ts/tsx/js/jsx/css/scss): // line comments and /* */ blocks.
  hash-family (py/sh/yml/toml):       # line comments.
  html-family (html/xml/svg):         <!-- --> blocks.
  data (json):                        reported as data, not code.
  md:                                  non-blank, non-comment counted as code.
"""
import re
import subprocess
import sys
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# extension -> (language, family)
LANGS = {
    ".ts": ("TypeScript", "c"), ".tsx": ("TypeScript", "c"),
    ".js": ("JavaScript", "c"), ".jsx": ("JavaScript", "c"),
    ".mjs": ("JavaScript", "c"), ".cjs": ("JavaScript", "c"),
    ".css": ("CSS", "c"), ".scss": ("SCSS", "c"),
    ".py": ("Python", "hash"), ".sh": ("Shell", "hash"),
    ".yml": ("YAML", "hash"), ".yaml": ("YAML", "hash"),
    ".toml": ("TOML", "hash"), ".html": ("HTML", "html"),
    ".xml": ("XML", "html"), ".svg": ("SVG", "html"),
    ".json": ("JSON", "data"), ".jsonc": ("JSON", "data"),
    ".md": ("Markdown", "md"), ".sql": ("SQL", "hash"),
}

# Binary assets: `wc -l` on a .png or a .gz reports bytes, not lines. Counting
# them inflates the total by hundreds of thousands and is meaningless.
BINARY_EXT = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".avif",
    ".gz", ".br", ".zip", ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".mp3", ".mp4", ".webm", ".wav", ".pdf", ".wasm", ".bin", ".onnx",
    ".pt", ".traineddata", ".db", ".sqlite",
}


GEN_MARKERS = re.compile(
    r"do not edit|do not modify|@generated|generated by wrangler|"
    r"generated by scripts/|generated by node|regenerate by|"
    r"auto-?generated from|this file is generated",
    re.I,
)

# Only a marker in the file HEADER identifies a generated file. Matching
# anywhere produced false positives: `BlogPost.tsx` imports `AutoGeneratedBadge`,
# `McpCatalog.tsx` documents that its *manifest* is auto-generated, and
# `tool-count.test.ts` tells you not to edit a constant. Those are hand-written
# files that merely mention generation.
GEN_HEADER_LINES = 12

# Markdown is prose; "generated" in a README never makes the doc machine-written.
GEN_EXTENSIONS = {".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".css", ".scss"}


def is_generated(path):
    """A generated source file is excluded from the hand-written total.

    Generated *data* (public/data, threat-intel-staging) is already split out by
    directory. This catches generated *source* — the `wrangler types` type stub
    and files emitted by the build scripts — which is committed but not written
    by a human and would otherwise inflate a codebase-size number by ~30k lines.
    """
    ext = os.path.splitext(path)[1].lower()
    if ext not in GEN_EXTENSIONS:
        return False
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            head = []
            for _ in range(GEN_HEADER_LINES):
                line = fh.readline()
                if not line:
                    break
                head.append(line)
    except OSError:
        return False
    return bool(GEN_MARKERS.search("".join(head)))


def classify(path):
    _, ext = os.path.splitext(path)
    return LANGS.get(ext.lower())


def count_file(path, family):
    """Return (blank, comment, code) line counts."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            raw = fh.read()
    except (OSError, UnicodeError):
        return (0, 0, 0)

    lines = raw.split("\n")
    # A trailing newline produces a final empty element; drop it.
    if lines and lines[-1] == "":
        lines.pop()

    blank = comment = code = 0
    in_block = False

    for line in lines:
        stripped = line.strip()

        if in_block:
            comment += 1
            if "*/" in stripped:
                in_block = False
            continue

        if stripped == "":
            blank += 1
            continue

        if family == "c":
            if stripped.startswith("//"):
                comment += 1
                continue
            if stripped.startswith("/*"):
                comment += 1
                if "*/" not in stripped:
                    in_block = True
                continue
            # Code with a trailing line comment still counts as code.
            code += 1
        elif family == "hash":
            if stripped.startswith("#"):
                comment += 1
            else:
                code += 1
        elif family == "html":
            if stripped.startswith("<!--"):
                comment += 1
                if "-->" not in stripped:
                    in_block = True
                continue
            code += 1
        elif family == "md":
            code += 1
        elif family == "data":
            # cloc reports JSON as data lines, not source.
            code += 1

    return (blank, comment, code)


def main():
    tracked = subprocess.run(
        ["git", "-C", ROOT, "ls-files", "-z"],
        capture_output=True, text=True, check=True,
    ).stdout.split("\0")

    by_lang = defaultdict(lambda: [0, 0, 0, 0])  # files, blank, comment, code
    by_dir = defaultdict(lambda: [0, 0, 0, 0])
    lang_data = defaultdict(lambda: [0, 0, 0, 0])
    dir_data = defaultdict(lambda: [0, 0, 0, 0])
    gen_lang = defaultdict(lambda: [0, 0, 0, 0])
    gen_files = []
    unclassified = defaultdict(int)

    def bucket(rel, lang, blank, comment, code):
        """Split generated data and generated source from hand-written code."""
        full = os.path.join(ROOT, rel)
        is_data = rel.startswith("public/data/") or rel.startswith("threat-intel-staging/")
        if is_data:
            lang_row, dir_row = lang_data, dir_data
        elif is_generated(full):
            lang_row, dir_row = gen_lang, None
            gen_files.append(rel)
        else:
            lang_row, dir_row = by_lang, by_dir

        row = lang_row[lang]
        row[0] += 1
        row[1] += blank
        row[2] += comment
        row[3] += code

        # Generated source is tracked by language only — no dir breakdown.
        if dir_row is not None:
            top = rel.split("/")[0] if "/" in rel else "(root)"
            d = dir_row[top]
            d[0] += 1
            d[1] += blank
            d[2] += comment
            d[3] += code

    for rel in tracked:
        if not rel:
            continue
        ext = os.path.splitext(rel)[1].lower()
        if ext in BINARY_EXT:
            continue
        info = classify(rel)
        if info is None:
            base = os.path.basename(rel)
            if "." not in base:
                unclassified["(no extension)"] += 1
            continue
        lang, family = info
        blank, comment, code = count_file(os.path.join(ROOT, rel), family)
        bucket(rel, lang, blank, comment, code)

    def emit(title, data, limit=None):
        rows = sorted(data.items(), key=lambda kv: kv[1][3], reverse=True)
        if limit:
            rows = rows[:limit]
        print(f"\n{title}")
        print(f"  {'name':<26} {'files':>7} {'blank':>9} {'comment':>9} {'code':>9} {'total':>9}")
        print("  " + "-" * 72)
        for name, (f, b, c, code) in rows:
            print(f"  {name:<26} {f:>7} {b:>9} {c:>9} {code:>9} {b+c+code:>9}")
        tf = sum(v[0] for _, v in rows); tb = sum(v[1] for _, v in rows)
        tc = sum(v[2] for _, v in rows); tk = sum(v[3] for _, v in rows)
        print("  " + "-" * 72)
        print(f"  {'TOTAL':<26} {tf:>7} {tb:>9} {tc:>9} {tk:>9} {tb+tc+tk:>9}")

    emit("SOURCE — BY LANGUAGE (excludes public/data)", by_lang)

    src = {k: v for k, v in by_lang.items() if k not in ("JSON", "Markdown")}
    tf = sum(v[0] for v in src.values()); tb = sum(v[1] for v in src.values())
    tc = sum(v[2] for v in src.values()); tk = sum(v[3] for v in src.values())
    print(f"\nHAND-WRITTEN CODE ONLY (excludes JSON + Markdown prose)")
    print(f"  files={tf}  blank={tb}  comment={tc}  CODE={tk}  total={tb+tc+tk}")

    emit("SOURCE — BY TOP-LEVEL DIRECTORY", by_dir)

    if lang_data:
        emit("GENERATED DATA (public/data + threat-intel-staging) — separately", lang_data)
        print("  ^ generated/committed upstream data, not hand-written code")

    if gen_lang:
        emit("GENERATED SOURCE (wrangler types / build scripts)", gen_lang)
        print("  ^ committed but machine-written:")
        for rel in sorted(gen_files):
            print(f"      {rel}")


if __name__ == "__main__":
    main()