/**
 * BUILD-GENERATED — do not edit by hand. Regenerated by scripts/generate-og-version.mjs.
 *
 * Baked into every dynamic OG-card URL (`/og-image/v<ver>/page/<id>.png`) so
 * each deploy emits brand-new og:image / twitter:image URLs. X/Twitter caches
 * card metadata (including image-fetch failures) per URL for days; a per-deploy
 * version segment forces a clean re-crawl of every card after each deploy.
 */
export const OG_BUILD_VERSION = 'v2ef50078f';
